// Auto-generated by scripts/register-template-manifests.ts. Do not edit.
import { manifest as manifest0 } from "./ao-dai-hue.manifest";
import { manifest as manifest1 } from "./arch-sage.manifest";
import { manifest as manifest2 } from "./art-deco-gatsby.manifest";
import { manifest as manifest3 } from "./aurora-glass-dark.manifest";
import { manifest as manifest4 } from "./ban-ve-to-am.manifest";
import { manifest as manifest5 } from "./bat-trang-blue.manifest";
import { manifest as manifest6 } from "./botanical-lavender.manifest";
import { manifest as manifest7 } from "./celestial-map.manifest";
import { manifest as manifest8 } from "./chim-lac-ivory.manifest";
import { manifest as manifest9 } from "./cinema-credit.manifest";
import { manifest as manifest10 } from "./coastal-mediterranean.manifest";
import { manifest as manifest11 } from "./coi-trau-kham-trai.manifest";
import { manifest as manifest12 } from "./comic-hero-assemble.manifest";
import { manifest as manifest13 } from "./cong-la-dua-mien-tay.manifest";
import { manifest as manifest14 } from "./crystal-floral-red.manifest";
import { manifest as manifest15 } from "./detective-conan-casebook.manifest";
import { manifest as manifest16 } from "./dong-ho-folk.manifest";
import { manifest as manifest17 } from "./doraemon-door.manifest";
import { manifest as manifest18 } from "./editorial-noir.manifest";
import { manifest as manifest19 } from "./hai-yen-thanh-thu.manifest";
import { manifest as manifest20 } from "./hang-trong-folk.manifest";
import { manifest as manifest21 } from "./hoa-kho-orange.manifest";
import { manifest as manifest22 } from "./hoa-thu-do-ruou-vang.manifest";
import { manifest as manifest23 } from "./hoa-thu-hong.manifest";
import { manifest as manifest24 } from "./hoa-thu-xanh-duong.manifest";
import { manifest as manifest25 } from "./hoa-thu-xanh-la.manifest";
import { manifest as manifest26 } from "./hong-van-rose.manifest";
import { manifest as manifest27 } from "./hy-uoc.manifest";
import { manifest as manifest28 } from "./ivory-signature.manifest";
import { manifest as manifest29 } from "./long-phung-deco.manifest";
import { manifest as manifest30 } from "./long-phung-gatefold.manifest";
import { manifest as manifest31 } from "./mahal-gold.manifest";
import { manifest as manifest32 } from "./minimalism-dark-blue.manifest";
import { manifest as manifest33 } from "./nguyet-anh-sleeve.manifest";
import { manifest as manifest34 } from "./nguyet-bach.manifest";
import { manifest as manifest35 } from "./phong-thu-be.manifest";
import { manifest as manifest36 } from "./phong-thu-do-pastel.manifest";
import { manifest as manifest37 } from "./phong-thu-hong-pastel.manifest";
import { manifest as manifest38 } from "./phong-thu-lam-pastel.manifest";
import { manifest as manifest39 } from "./phong-thu-luc-pastel.manifest";
import { manifest as manifest40 } from "./porcelain-blue.manifest";
import { manifest as manifest41 } from "./porcelain-brown.manifest";
import { manifest as manifest42 } from "./porcelain-red.manifest";
import { manifest as manifest43 } from "./porcelain-v2-green.manifest";
import { manifest as manifest44 } from "./porcelain-v2-red.manifest";
import { manifest as manifest45 } from "./rap-hy-sai-gon.manifest";
import { manifest as manifest46 } from "./riso-duotone.manifest";
import { manifest as manifest47 } from "./royal-v2-green.manifest";
import { manifest as manifest48 } from "./sen-monoline.manifest";
import { manifest as manifest49 } from "./son-mai-lacquer.manifest";
import { manifest as manifest50 } from "./swiss-brutalist.manifest";
import { manifest as manifest51 } from "./thanh-duong-anh-sang.manifest";
import { manifest as manifest52 } from "./thap-nhi-chi-do.manifest";
import { manifest as manifest53 } from "./tho-cam-highland.manifest";
import { manifest as manifest54 } from "./ticket-terracotta.manifest";
import { manifest as manifest55 } from "./to-hong.manifest";
import { manifest as manifest56 } from "./trong-dong-dong-son.manifest";
import { manifest as manifest57 } from "./truc-chi-minimal.manifest";
import { manifest as manifest58 } from "./uyen-uong.manifest";
import { manifest as manifest59 } from "./y2k-chrome.manifest";
import { manifest as manifest60 } from "./zen-sand.manifest";

import type { ChungDoiDemoContent } from "@/data/chungdoi-demo-content";
import type { ChungDoiThemeConfig } from "@/data/chungdoi-theme-config";
import type { ChungDoiTemplate } from "@/data/chungdoi";
import type { TemplateCeremonyRendering } from "./template-manifest";
import { TEMPLATE_MANIFEST_LOCALES } from "./template-manifest";

export const generatedTemplateManifests = [
  manifest0,
  manifest1,
  manifest2,
  manifest3,
  manifest4,
  manifest5,
  manifest6,
  manifest7,
  manifest8,
  manifest9,
  manifest10,
  manifest11,
  manifest12,
  manifest13,
  manifest14,
  manifest15,
  manifest16,
  manifest17,
  manifest18,
  manifest19,
  manifest20,
  manifest21,
  manifest22,
  manifest23,
  manifest24,
  manifest25,
  manifest26,
  manifest27,
  manifest28,
  manifest29,
  manifest30,
  manifest31,
  manifest32,
  manifest33,
  manifest34,
  manifest35,
  manifest36,
  manifest37,
  manifest38,
  manifest39,
  manifest40,
  manifest41,
  manifest42,
  manifest43,
  manifest44,
  manifest45,
  manifest46,
  manifest47,
  manifest48,
  manifest49,
  manifest50,
  manifest51,
  manifest52,
  manifest53,
  manifest54,
  manifest55,
  manifest56,
  manifest57,
  manifest58,
  manifest59,
  manifest60,
] as const;

export type GeneratedTemplateSlug = (typeof generatedTemplateManifests)[number]["slug"];

export const generatedTemplateSlugs = generatedTemplateManifests.map(
  (manifest) => manifest.slug,
) as GeneratedTemplateSlug[];

export const generatedTemplateRouteSlugs = generatedTemplateManifests.map(
  (manifest) => [manifest.slug, manifest.viRouteSlug] as const,
);

export const generatedTemplates: ChungDoiTemplate[] = generatedTemplateManifests.map(
  (manifest) => {
    const previewStem = manifest.slug.replaceAll("-", "_");
    return {
      slug: manifest.slug,
      ...manifest.catalog,
      listing: `/chungdoi/images/template-previews/en/listing/${previewStem}.webp`,
      portrait: `/chungdoi/images/template-previews/en/portrait/${previewStem}.webp`,
      landscape: `/chungdoi/images/template-previews/en/landscape/${previewStem}.webp`,
      sourceUrl: `https://thiepmungonline.com/mau-thiep/${manifest.viRouteSlug}/demo`,
    };
  },
);

export const generatedDemoContent = Object.fromEntries(
  generatedTemplateManifests.map((manifest) => [manifest.slug, manifest.demoContent]),
) as unknown as Record<GeneratedTemplateSlug, ChungDoiDemoContent>;

export const generatedThemeConfigs = Object.fromEntries(
  generatedTemplateManifests.map((manifest) => [manifest.slug, manifest.theme]),
) as unknown as Record<GeneratedTemplateSlug, ChungDoiThemeConfig>;

export const generatedTemplateCeremonyRendering = Object.fromEntries(
  generatedTemplateManifests.map((manifest) => [manifest.slug, manifest.ceremonyRendering]),
) as unknown as Record<GeneratedTemplateSlug, TemplateCeremonyRendering>;

export const generatedListingMessages = Object.fromEntries(
  TEMPLATE_MANIFEST_LOCALES.map((locale) => [
    locale,
    Object.fromEntries(
      generatedTemplateManifests.map((manifest) => [manifest.slug, manifest.i18n[locale]]),
    ),
  ]),
) as unknown as Record<
  (typeof TEMPLATE_MANIFEST_LOCALES)[number],
  Record<GeneratedTemplateSlug, { name: string; description: string }>
>;
