// Auto-generated by scripts/register-template-manifests.ts. Do not edit.
import { manifest as manifest0 } from "./ao-dai-hue.manifest";
import { manifest as manifest1 } from "./arch-sage.manifest";
import { manifest as manifest2 } from "./art-deco-gatsby.manifest";
import { manifest as manifest3 } from "./aurora-glass-dark.manifest";
import { manifest as manifest4 } from "./bat-trang-blue.manifest";
import { manifest as manifest5 } from "./botanical-lavender.manifest";
import { manifest as manifest6 } from "./celestial-map.manifest";
import { manifest as manifest7 } from "./cinema-credit.manifest";
import { manifest as manifest8 } from "./coastal-mediterranean.manifest";
import { manifest as manifest9 } from "./dong-ho-folk.manifest";
import { manifest as manifest10 } from "./editorial-noir.manifest";
import { manifest as manifest11 } from "./hang-trong-folk.manifest";
import { manifest as manifest12 } from "./long-phung-deco.manifest";
import { manifest as manifest13 } from "./riso-duotone.manifest";
import { manifest as manifest14 } from "./sen-monoline.manifest";
import { manifest as manifest15 } from "./son-mai-lacquer.manifest";
import { manifest as manifest16 } from "./swiss-brutalist.manifest";
import { manifest as manifest17 } from "./tho-cam-highland.manifest";
import { manifest as manifest18 } from "./ticket-terracotta.manifest";
import { manifest as manifest19 } from "./truc-chi-minimal.manifest";
import { manifest as manifest20 } from "./y2k-chrome.manifest";
import { manifest as manifest21 } from "./zen-sand.manifest";

import type { ChungDoiDemoContent } from "@/data/chungdoi-demo-content";
import type { ChungDoiThemeConfig } from "@/data/chungdoi-theme-config";
import type { ChungDoiTemplate } from "@/data/chungdoi";
import { TEMPLATE_MANIFEST_LOCALES } from "./template-manifest";

export const generatedTemplateManifests = [
  manifest0,
  manifest1,
  manifest2,
  manifest3,
  manifest4,
  manifest5,
  manifest6,
  manifest7,
  manifest8,
  manifest9,
  manifest10,
  manifest11,
  manifest12,
  manifest13,
  manifest14,
  manifest15,
  manifest16,
  manifest17,
  manifest18,
  manifest19,
  manifest20,
  manifest21,
] as const;

export type GeneratedTemplateSlug = (typeof generatedTemplateManifests)[number]["slug"];

export const generatedTemplateSlugs = generatedTemplateManifests.map(
  (manifest) => manifest.slug,
) as GeneratedTemplateSlug[];

export const generatedTemplateRouteSlugs = generatedTemplateManifests.map(
  (manifest) => [manifest.slug, manifest.viRouteSlug] as const,
);

export const generatedTemplates: ChungDoiTemplate[] = generatedTemplateManifests.map(
  (manifest) => {
    const previewStem = manifest.slug.replaceAll("-", "_");
    return {
      slug: manifest.slug,
      ...manifest.catalog,
      listing: `/chungdoi/images/template-previews/en/listing/${previewStem}.webp`,
      portrait: `/chungdoi/images/template-previews/en/portrait/${previewStem}.webp`,
      landscape: `/chungdoi/images/template-previews/en/landscape/${previewStem}.webp`,
      sourceUrl: `https://thiepmungonline.com/mau-thiep/${manifest.viRouteSlug}/demo`,
    };
  },
);

export const generatedDemoContent = Object.fromEntries(
  generatedTemplateManifests.map((manifest) => [manifest.slug, manifest.demoContent]),
) as unknown as Record<GeneratedTemplateSlug, ChungDoiDemoContent>;

export const generatedThemeConfigs = Object.fromEntries(
  generatedTemplateManifests.map((manifest) => [manifest.slug, manifest.theme]),
) as unknown as Record<GeneratedTemplateSlug, ChungDoiThemeConfig>;

export const generatedListingMessages = Object.fromEntries(
  TEMPLATE_MANIFEST_LOCALES.map((locale) => [
    locale,
    Object.fromEntries(
      generatedTemplateManifests.map((manifest) => [manifest.slug, manifest.i18n[locale]]),
    ),
  ]),
) as unknown as Record<
  (typeof TEMPLATE_MANIFEST_LOCALES)[number],
  Record<GeneratedTemplateSlug, { name: string; description: string }>
>;
