#!/usr/bin/env python3
"""Online DB backup + deduplicated immutable-upload snapshot, retain seven days.

Only dated directories generated by this program are eligible for retention.
Historical migration backups live elsewhere and are never touched.
"""
import datetime
import fcntl
import os
import pathlib
import re
import shutil
import sqlite3
import subprocess

root = pathlib.Path("/srv/thiepmungonline")
assert (root / "LIVE").is_file()
os.umask(0o077)
lock = (root / "ops/backup.lock").open("a")
fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
parent = root / "backups"
parent.mkdir(exist_ok=True)
now = datetime.datetime.now(datetime.timezone.utc)
target = parent / now.strftime("%Y%m%dT%H%M%SZ")
target.mkdir()
source = sqlite3.connect(f"file:{root / 'data/prod.db'}?mode=ro", uri=True, timeout=30)
dest = sqlite3.connect(target / "prod.db")
source.backup(dest, pages=256, sleep=0.1)
assert dest.execute("PRAGMA quick_check").fetchone()[0] == "ok"
dest.close()
source.close()
previous = sorted(p for p in parent.iterdir() if re.fullmatch(r"\d{8}T\d{6}Z", p.name) and p != target and (p / "COMPLETE").is_file())
for name in ["editor-uploads", "guest-media", "blog-media", "slideshow-media"]:
    source_dir = root / "data" / name
    destination_dir = target / name
    if not source_dir.is_dir():
        destination_dir.mkdir()
        continue
    args = ["rsync", "-a"]
    if previous and (previous[-1] / name).is_dir():
        args.append("--link-dest=" + str(previous[-1] / name))
    args += [str(source_dir) + "/", str(destination_dir) + "/"]
    subprocess.run(args, check=True)
for name in [".env", "tunnel.env", "compose.yaml"]:
    shutil.copy2(root / name, target / name)
(target / "COMPLETE").touch()
cutoff = now - datetime.timedelta(days=7)
for old in previous:
    timestamp = datetime.datetime.strptime(old.name, "%Y%m%dT%H%M%SZ").replace(tzinfo=datetime.timezone.utc)
    if timestamp < cutoff:
        assert old.parent == parent and not old.is_symlink()
        shutil.rmtree(old)
print("backup_ok", target.name, "sqlite=ok")
