import { existsSync } from "node:fs";
import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

import {
  TEMPLATE_MANIFEST_LOCALES,
  type TemplateManifest,
} from "../src/data/templates/template-manifest";
import { assertValidArtOpeningEffect } from "../src/data/templates/opening-effect";

const root = process.cwd();
const manifestDirectory = path.join(root, "src/data/templates");
const generatedDataFile = path.join(manifestDirectory, "generated-data.ts");
const generatedRendererFile = path.join(
  root,
  "src/components/generated/template-renderers.tsx",
);

type LoadedManifest = {
  fileName: string;
  manifest: TemplateManifest;
};

function fail(message: string): never {
  throw new Error(`[template registrar] ${message}`);
}

function assertNonEmpty(value: string, label: string, fileName: string) {
  if (!value.trim()) fail(`${fileName}: ${label} không được để trống`);
}

function validateManifest({ fileName, manifest }: LoadedManifest) {
  const expectedSlug = fileName.replace(/\.manifest\.ts$/, "");
  if (manifest.slug !== expectedSlug) {
    fail(`${fileName}: slug phải là ${expectedSlug}, nhận ${manifest.slug}`);
  }

  assertNonEmpty(manifest.viRouteSlug, "viRouteSlug", fileName);
  assertNonEmpty(manifest.rendererExport, "rendererExport", fileName);
  if (!["inline-all", "post-template"].includes(manifest.ceremonyRendering)) {
    fail(`${fileName}: ceremonyRendering phải là inline-all hoặc post-template`);
  }
  assertNonEmpty(manifest.catalog.name, "catalog.name", fileName);
  assertNonEmpty(manifest.catalog.description, "catalog.description", fileName);
  if (manifest.demoContent.slug !== manifest.slug) {
    fail(`${fileName}: demoContent.slug phải khớp manifest.slug`);
  }

  for (const locale of TEMPLATE_MANIFEST_LOCALES) {
    const message = manifest.i18n[locale];
    if (!message) fail(`${fileName}: thiếu i18n.${locale}`);
    assertNonEmpty(message.name, `i18n.${locale}.name`, fileName);
    assertNonEmpty(message.description, `i18n.${locale}.description`, fileName);
  }

  const rendererPath = path.join(
    root,
    "src/components",
    `chungdoi-tpl-${manifest.slug}.tsx`,
  );
  if (!existsSync(rendererPath)) {
    fail(`${fileName}: thiếu renderer ${path.relative(root, rendererPath)}`);
  }

  for (const asset of manifest.assets) {
    if (!asset.startsWith("/")) {
      fail(`${fileName}: asset phải là public path bắt đầu bằng /: ${asset}`);
    }
    const assetPath = path.join(root, "public", asset.slice(1));
    if (!existsSync(assetPath)) {
      fail(`${fileName}: thiếu asset ${asset}`);
    }
  }

  const openingEffect = manifest.theme.openingEffect;
  if (openingEffect) {
    try {
      assertValidArtOpeningEffect(openingEffect);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      fail(`${fileName}: openingEffect không hợp lệ: ${message}`);
    }

    for (const asset of [
      openingEffect.plateSrc,
      ...openingEffect.layers.map((layer) => layer.src),
    ]) {
      if (!manifest.assets.includes(asset)) {
        fail(`${fileName}: openingEffect asset chưa có trong manifest.assets: ${asset}`);
      }
    }
  }
}

function assertUnique(
  loaded: readonly LoadedManifest[],
  select: (manifest: TemplateManifest) => string,
  label: string,
) {
  const ownerByValue = new Map<string, string>();
  for (const item of loaded) {
    const value = select(item.manifest);
    const owner = ownerByValue.get(value);
    if (owner) fail(`${label} trùng giữa ${owner} và ${item.fileName}: ${value}`);
    ownerByValue.set(value, item.fileName);
  }
}

function buildGeneratedData(loaded: readonly LoadedManifest[]) {
  const imports = loaded
    .map(
      (item, index) =>
        `import { manifest as manifest${index} } from "./${item.fileName.replace(/\.ts$/, "")}";`,
    )
    .join("\n");
  const manifests = loaded.map((_, index) => `manifest${index}`).join(",\n  ");

  return `// Auto-generated by scripts/register-template-manifests.ts. Do not edit.\n${imports}\n\nimport type { ChungDoiDemoContent } from "@/data/chungdoi-demo-content";\nimport type { ChungDoiThemeConfig } from "@/data/chungdoi-theme-config";\nimport type { ChungDoiTemplate } from "@/data/chungdoi";\nimport type { TemplateCeremonyRendering } from "./template-manifest";\nimport { TEMPLATE_MANIFEST_LOCALES } from "./template-manifest";\n\nexport const generatedTemplateManifests = [\n  ${manifests},\n] as const;\n\nexport type GeneratedTemplateSlug = (typeof generatedTemplateManifests)[number]["slug"];\n\nexport const generatedTemplateSlugs = generatedTemplateManifests.map(\n  (manifest) => manifest.slug,\n) as GeneratedTemplateSlug[];\n\nexport const generatedTemplateRouteSlugs = generatedTemplateManifests.map(\n  (manifest) => [manifest.slug, manifest.viRouteSlug] as const,\n);\n\nexport const generatedTemplates: ChungDoiTemplate[] = generatedTemplateManifests.map(\n  (manifest) => {\n    const previewStem = manifest.slug.replaceAll("-", "_");\n    return {\n      slug: manifest.slug,\n      ...manifest.catalog,\n      listing: \`/chungdoi/images/template-previews/en/listing/\${previewStem}.webp\`,\n      portrait: \`/chungdoi/images/template-previews/en/portrait/\${previewStem}.webp\`,\n      landscape: \`/chungdoi/images/template-previews/en/landscape/\${previewStem}.webp\`,\n      sourceUrl: \`https://thiepmungonline.com/mau-thiep/\${manifest.viRouteSlug}/demo\`,\n    };\n  },\n);\n\nexport const generatedDemoContent = Object.fromEntries(\n  generatedTemplateManifests.map((manifest) => [manifest.slug, manifest.demoContent]),\n) as Record<GeneratedTemplateSlug, ChungDoiDemoContent>;\n\nexport const generatedThemeConfigs = Object.fromEntries(\n  generatedTemplateManifests.map((manifest) => [manifest.slug, manifest.theme]),\n) as Record<GeneratedTemplateSlug, ChungDoiThemeConfig>;\n\nexport const generatedTemplateCeremonyRendering = Object.fromEntries(\n  generatedTemplateManifests.map((manifest) => [manifest.slug, manifest.ceremonyRendering]),\n) as Record<GeneratedTemplateSlug, TemplateCeremonyRendering>;\n\nexport const generatedListingMessages = Object.fromEntries(\n  TEMPLATE_MANIFEST_LOCALES.map((locale) => [\n    locale,\n    Object.fromEntries(\n      generatedTemplateManifests.map((manifest) => [manifest.slug, manifest.i18n[locale]]),\n    ),\n  ]),\n) as Record<\n  (typeof TEMPLATE_MANIFEST_LOCALES)[number],\n  Record<GeneratedTemplateSlug, { name: string; description: string }>\n>;\n`;
}

function buildGeneratedRenderers(loaded: readonly LoadedManifest[]) {
  const declarations = loaded
    .map(
      (item, index) =>
        `const TemplateRenderer${index} = dynamic(() => import("@/components/chungdoi-tpl-${item.manifest.slug}").then((module) => module.${item.manifest.rendererExport}));`,
    )
    .join("\n");
  const entries = loaded
    .map(
      (item, index) =>
        `  "${item.manifest.slug}": { component: TemplateRenderer${index}, ceremonyRendering: "${item.manifest.ceremonyRendering}" },`,
    )
    .join("\n");

  return `// Auto-generated by scripts/register-template-manifests.ts. Do not edit.\n"use client";\n\nimport dynamic from "next/dynamic";\n\nimport type { GeneratedTemplateSlug } from "@/data/templates/generated-data";\nimport type { TemplateRendererEntry } from "@/components/template-renderer-entry";\n\n${declarations}\n\nexport const GENERATED_TEMPLATE_RENDERERS = {\n${entries}\n} satisfies Record<GeneratedTemplateSlug, TemplateRendererEntry>;\n`;
}

function addSafeObjectFromEntriesCasts(source: string) {
  return source.replaceAll(
    ") as Record<",
    ") as unknown as Record<",
  );
}

async function loadManifests(): Promise<LoadedManifest[]> {
  const fileNames = (await readdir(manifestDirectory))
    .filter((fileName) => fileName.endsWith(".manifest.ts"))
    .sort((a, b) => a.localeCompare(b));

  if (!fileNames.length) fail("không tìm thấy file *.manifest.ts");

  const loaded = await Promise.all(
    fileNames.map(async (fileName) => {
      const moduleUrl = pathToFileURL(path.join(manifestDirectory, fileName)).href;
      const loadedModule = (await import(moduleUrl)) as { manifest?: TemplateManifest };
      if (!loadedModule.manifest) fail(`${fileName}: thiếu named export manifest`);
      return { fileName, manifest: loadedModule.manifest };
    }),
  );

  for (const item of loaded) validateManifest(item);
  assertUnique(loaded, (manifest) => manifest.slug, "slug");
  assertUnique(loaded, (manifest) => manifest.viRouteSlug, "viRouteSlug");
  const openingEffectOwners = new Map<string, string>();
  for (const item of loaded) {
    const effect = item.manifest.theme.openingEffect;
    if (!effect) continue;
    const owner = openingEffectOwners.get(effect.id);
    if (owner) fail(`openingEffect.id trùng giữa ${owner} và ${item.fileName}: ${effect.id}`);
    openingEffectOwners.set(effect.id, item.fileName);
  }
  return loaded;
}

async function main() {
  const loaded = await loadManifests();
  await Promise.all([
    writeFile(
      generatedDataFile,
      addSafeObjectFromEntriesCasts(buildGeneratedData(loaded)),
    ),
    writeFile(generatedRendererFile, buildGeneratedRenderers(loaded)),
  ]);
  process.stdout.write(`Đã đăng ký ${loaded.length} template manifest.\n`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
