// Auto-generated by scripts/extract-theme-configs.mjs
// Per-template visual design tokens reverse-engineered from chungdoi.com's demo bundle.
// Do not hand-edit; re-run the script to refresh.

export type ChungDoiCardImage = {
  src: string;
  className: string;
  flyOnOpen: boolean;
};

export type ChungDoiThemeConfig = {
  theme: {
    background: string;
    cardBg: string;
    textPrimary: string;
    textSecondary: string;
    accent: string;
    dividerFrom: string;
    dividerTo: string;
    buttonBg: string;
    buttonText: string;
    guestBoxBg: string;
    guestBoxBorder?: string | null;
    particleColors: string[];
    particleType: string;
  };
  fonts: { couple: string | null; ampersand: string | null };
  sealType: string | null;
  decorations: { cardImages: ChungDoiCardImage[] };
};

export const chungdoiThemeConfig: Record<string, ChungDoiThemeConfig> = {
  "song-hy-green": {
    "theme": {
      "background": "linear-gradient(to bottom right, #0a1f0e, #122418, #1F3A25)",
      "cardBg": "#1F3A25",
      "textPrimary": "#e8f0e4",
      "textSecondary": "rgba(232, 240, 228, 0.85)",
      "accent": "#e8f0e4",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(232, 240, 228, 0.5)",
      "buttonBg": "#e8f0e4",
      "buttonText": "#1F3A25",
      "guestBoxBg": "rgba(0, 0, 0, 0.15)",
      "guestBoxBorder": "rgba(232, 240, 228, 0.3)",
      "particleColors": [
        "#a8e6a3",
        "#7bc47a",
        "#4CAF50",
        "#c8e6c9"
      ],
      "particleType": "happiness"
    },
    "fonts": {
      "couple": "\"Fz Aghita\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": "happiness",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[220px] md:w-[300px] -top-[65px] -left-[124px] md:-top-[104px] md:-left-[130px] opacity-[0.15] rotate-[30deg] md:rotate-[30deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/song-hy-red/chu-hy.webp"
        },
        {
          "className": "w-[220px] md:w-[300px] -bottom-[39px] -right-[156px] md:-bottom-[104px] md:-right-[143px] opacity-[0.15] -rotate-[-30deg] md:-rotate-[-30deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/song-hy-red/chu-hy.webp"
        }
      ]
    }
  },
  "double-phoenix-red": {
    "theme": {
      "background": "linear-gradient(to bottom right, #710001, #5a0001, #450001)",
      "cardBg": "rgba(255, 240, 231, 0.95)",
      "textPrimary": "#710001",
      "textSecondary": "rgba(113, 0, 1, 0.8)",
      "accent": "#710001",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(113, 0, 1, 0.5)",
      "buttonBg": "#710001",
      "buttonText": "#FFF0E7",
      "guestBoxBg": "rgba(113, 0, 1, 0.1)",
      "particleColors": [
        "#710001",
        "#8B0000",
        "#A52A2A",
        "#FFF0E7"
      ],
      "particleType": "happiness"
    },
    "fonts": {
      "couple": "\"Fz Aghita\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": null,
    "decorations": {
      "cardImages": [
        {
          "className": "w-[120px] md:w-[220px] -top-[20px] -left-[70px] md:-top-[20px] md:-left-[110px] opacity-90 rotate-10",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/songphung-red/Phuong.webp"
        },
        {
          "className": "w-[140px] md:w-[220px] -bottom-[120px] -right-[90px]  md:-bottom-[110px] md:-right-[110px] opacity-90 -scale-x-100 rotate-5",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/songphung-red/Phuong.webp"
        },
        {
          "className": "w-[120px] md:w-[160px] -bottom-[20px] -left-[20px] md:-bottom-[30px] md:-left-[30px] opacity-60",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/songphung-red/HOA.webp"
        },
        {
          "className": "w-[100px] md:w-[140px] -top-[15px] -right-[15px] md:-top-[20px] md:-right-[20px] opacity-60 rotate-180",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/songphung-red/HOA.webp"
        }
      ]
    }
  },
  "spring-garden-red": {
    "theme": {
      "background": "linear-gradient(to bottom right, #fff5f5, #ffefef, #ffe8e8)",
      "cardBg": "rgba(255, 255, 255, 0.95)",
      "textPrimary": "#D25F65",
      "textSecondary": "rgba(210, 95, 101, 0.7)",
      "accent": "#b54b51",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(181, 75, 81, 0.5)",
      "buttonBg": "#D25F65",
      "buttonText": "#ffffff",
      "guestBoxBg": "rgba(255, 255, 255, 0.6)",
      "particleColors": [
        "#FF6B6B",
        "#FFB6C1",
        "#FFC0CB",
        "#f5c4c8"
      ],
      "particleType": "leaves"
    },
    "fonts": {
      "couple": "\"UNI Chu truyen thong\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[300px] md:w-[420px] -top-[40px] -right-[50px] md:-top-[60px] md:-right-[70px] opacity-60",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/vuon-xuan-red/top-right.webp"
        },
        {
          "className": "w-[300px] md:w-[420px] -bottom-[40px] -left-[50px] md:-bottom-[60px] md:-left-[70px] opacity-60",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/vuon-xuan-red/button-left.webp"
        }
      ]
    }
  },
  "double-dragon-green": {
    "theme": {
      "background": "linear-gradient(to bottom right, #0f2215, #0a180e, #061008)",
      "cardBg": "#1a3a22",
      "textPrimary": "#f0d497",
      "textSecondary": "rgba(240, 212, 151, 0.85)",
      "accent": "#f0d497",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(240, 212, 151, 0.5)",
      "buttonBg": "#f0d497",
      "buttonText": "#1a3a22",
      "guestBoxBg": "rgba(0, 0, 0, 0.15)",
      "guestBoxBorder": "rgba(240, 212, 151, 0.3)",
      "particleColors": [
        "#FFD700",
        "#FFC107",
        "#90EE90",
        "#FFE066"
      ],
      "particleType": "happiness"
    },
    "fonts": {
      "couple": "\"Fz Aghita\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": null,
    "decorations": {
      "cardImages": [
        {
          "className": "w-[220px] md:w-[300px] -top-[50px] -left-[95px] md:-top-[80px] md:-left-[100px] opacity-30 rotate-[30deg] md:rotate-[30deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/songlong-red/dragon_left.webp"
        },
        {
          "className": "w-[220px] md:w-[300px] -bottom-[30px] -right-[120px] md:-bottom-[80px] md:-right-[110px] opacity-30 -rotate-[-30deg] md:-rotate-[-30deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/songlong-red/dragon_right.webp"
        },
        {
          "className": "w-[50px] md:w-[70px] top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-15",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/songlong-red/chinese_happiness.webp"
        },
        {
          "className": "w-[50px] md:w-[70px] top-3 right-3 md:top-4 md:right-4 opacity-40",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/songlong-red/cloud_small.webp"
        },
        {
          "className": "w-[50px] md:w-[70px] bottom-3 left-3 md:bottom-4 md:left-4 opacity-40 -scale-x-100",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/songlong-red/cloud_big.webp"
        },
        {
          "className": "w-[50px] md:w-[70px] bottom-2 left-1/2 -translate-x-1/2 opacity-20",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/songlong-red/wave.webp"
        }
      ]
    }
  },
  "dragon-phoenix-v3-red": {
    "theme": {
      "background": "linear-gradient(to bottom right, #710001, #5a0001, #450001)",
      "cardBg": "rgba(255, 190, 137, 0.1)",
      "textPrimary": "#FFBE89",
      "textSecondary": "rgba(255, 190, 137, 0.8)",
      "accent": "#FFBE89",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(255, 190, 137, 0.5)",
      "buttonBg": "#FFBE89",
      "buttonText": "#710001",
      "guestBoxBg": "rgba(255, 190, 137, 0.08)",
      "guestBoxBorder": "rgba(255, 190, 137, 0.25)",
      "particleColors": [
        "#FFBE89",
        "#FFD4A8",
        "#FF9B4A",
        "#710001"
      ],
      "particleType": "happiness"
    },
    "fonts": {
      "couple": "\"Fz Qellia\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": null,
    "decorations": {
      "cardImages": [
        {
          "className": "w-[230px] md:w-[320px] top-[10px] -left-[20px] md:top-[0px] md:-left-[30px] opacity-55 rotate-[20deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/longphung-v3-red/phung.webp"
        },
        {
          "className": "w-[230px] md:w-[320px] bottom-[10px] -right-[20px] md:bottom-[0px] md:-right-[30px] opacity-55 -rotate-[20deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/longphung-v3-red/rong.webp"
        }
      ]
    }
  },
  "chibi-red": {
    "theme": {
      "background": "#fef0e0",
      "cardBg": "#fef8f0",
      "textPrimary": "#9e2a2b",
      "textSecondary": "rgba(158, 42, 43, 0.75)",
      "accent": "#c44d4d",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(196, 77, 77, 0.5)",
      "buttonBg": "#9e2a2b",
      "buttonText": "#fef0e0",
      "guestBoxBg": "rgba(158, 42, 43, 0.08)",
      "particleColors": [
        "#CC0033",
        "#B80030",
        "#FF0040",
        "#AA0028"
      ],
      "particleType": "confetti"
    },
    "fonts": {
      "couple": "\"1FTV VIP Signora\", \"Dancing Script\", cursive",
      "ampersand": null
    },
    "sealType": null,
    "decorations": {
      "cardImages": [
        {
          "className": "w-[50px] md:w-[70px] top-[60px] -left-[5px] md:top-[45px] md:left-[10px]",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/chibi_red/cherry-blossom.webp"
        },
        {
          "className": "w-[45px] md:w-[65px] top-[65px] -right-[5px] md:top-[48px] md:right-[10px] -scale-x-100",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/chibi_red/cherry-blossom.webp"
        },
        {
          "className": "w-[30px] md:w-[40px] top-[30px] right-[20px] md:top-[25px] md:right-[30px] opacity-30",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/chibi_red/decorative-diamond.webp"
        },
        {
          "className": "w-[25px] md:w-[35px] bottom-[40px] left-[15px] md:bottom-[30px] md:left-[25px] opacity-25 rotate-12",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/chibi_red/decorative-diamond.webp"
        },
        {
          "className": "w-full top-0 left-0",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/chibi_red/decorative-flowers.webp"
        },
        {
          "className": "w-[200px] md:w-[250px] top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-5",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/chibi_red/couple-main.webp"
        }
      ]
    }
  },
  "glass-garden-green": {
    "theme": {
      "background": "#eef3e8 url(__ASSET_VAR__) center / 180% auto repeat",
      "cardBg": "rgba(255, 255, 255, 0.3)",
      "textPrimary": "#47613e",
      "textSecondary": "rgba(53, 69, 47, 0.8)",
      "accent": "#47613e",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(71, 97, 62, 0.35)",
      "buttonBg": "#47613e",
      "buttonText": "#ffffff",
      "guestBoxBg": "rgba(71, 97, 62, 0.08)",
      "particleColors": [
        "#dbe6d0",
        "#c4d4b3",
        "#ffffff",
        "#e7eede"
      ],
      "particleType": "flowers"
    },
    "fonts": {
      "couple": "\"DFVN New Eddy\", \"Fz Qellia\", cursive",
      "ampersand": null
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[52%] max-w-[260px] md:max-w-[300px] top-0 right-0 translate-x-[14%] -translate-y-[14%] rotate-[-15deg] opacity-90",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/glass-garden-green/flower2-decoration.webp"
        },
        {
          "className": "w-[52%] max-w-[260px] md:max-w-[300px] top-0 left-0 -translate-x-[14%] -translate-y-[14%] rotate-[15deg] -scale-x-100 opacity-90",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/glass-garden-green/flower2-decoration.webp"
        },
        {
          "className": "w-[96%] max-w-[440px] md:max-w-[500px] bottom-0 left-1/2 -translate-x-1/2 translate-y-[45%] opacity-90",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/glass-garden-green/flower5-bottom.webp"
        }
      ]
    }
  },
  "spring-garden-blue": {
    "theme": {
      "background": "linear-gradient(to bottom right, #f0f7fa, #e8f2f6, #dfedf2)",
      "cardBg": "rgba(255, 255, 255, 0.95)",
      "textPrimary": "#486C7D",
      "textSecondary": "rgba(72, 108, 125, 0.7)",
      "accent": "#3a5666",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(58, 86, 102, 0.5)",
      "buttonBg": "#486C7D",
      "buttonText": "#ffffff",
      "guestBoxBg": "rgba(255, 255, 255, 0.6)",
      "particleColors": [
        "#87CEEB",
        "#B0E0E6",
        "#E0FFFF",
        "#a4c4d4"
      ],
      "particleType": "leaves"
    },
    "fonts": {
      "couple": "\"UNI Chu truyen thong\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[840px] md:w-[800px] top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-60",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/vuon-xuan-blue/button.webp"
        }
      ]
    }
  },
  "spring-garden-green": {
    "theme": {
      "background": "linear-gradient(to bottom right, #f0f4ef, #e8ede6, #dfe5dd)",
      "cardBg": "rgba(255, 255, 255, 0.95)",
      "textPrimary": "#5d6a57",
      "textSecondary": "rgba(93, 106, 87, 0.7)",
      "accent": "#697a62",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(105, 122, 98, 0.5)",
      "buttonBg": "#5d6a57",
      "buttonText": "#ffffff",
      "guestBoxBg": "rgba(255, 255, 255, 0.6)",
      "particleColors": [
        "#5d6a57",
        "#697a62",
        "#8a9e82",
        "#bdcdc1"
      ],
      "particleType": "leaves"
    },
    "fonts": {
      "couple": "\"UNI Chu truyen thong\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[1200px] md:w-[1680px] -top-[100px] -right-[100px] md:-top-[140px] md:-right-[140px] opacity-70",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/nature/flower_top.webp"
        },
        {
          "className": "w-[1200px] md:w-[1680px] -bottom-[100px] -left-[100px] md:-bottom-[140px] md:-left-[140px] opacity-70 rotate-180",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/nature/flower_paralax.webp"
        }
      ]
    }
  },
  "boho-floral-green": {
    "theme": {
      "background": "linear-gradient(to bottom right, #1a3005, #0f2003, #081500)",
      "cardBg": "rgba(255, 250, 247, 0.95)",
      "textPrimary": "#30530F",
      "textSecondary": "rgba(48, 83, 15, 0.7)",
      "accent": "#6B8040",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(48, 83, 15, 0.5)",
      "buttonBg": "#30530F",
      "buttonText": "#FFFAF7",
      "guestBoxBg": "rgba(48, 83, 15, 0.1)",
      "particleColors": [
        "#8bc34a",
        "#6B8040",
        "#a5c862",
        "#c8dfa0"
      ],
      "particleType": "leaves"
    },
    "fonts": {
      "couple": "\"Fz Aghita\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[400px] md:w-[400px] -top-[40px] left-[calc(-30%-50px)] md:-top-[50px] md:left-[-30%] opacity-40",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/boho-floral-green/flower.webp"
        },
        {
          "className": "w-[160px] md:w-[220px] -bottom-[40px] -right-[40px] md:-bottom-[60px] md:-right-[50px] opacity-30 rotate-[160deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/boho-floral-green/flower.webp"
        }
      ]
    }
  },
  "chateau-green": {
    "theme": {
      "background": "linear-gradient(to bottom right, #1e3a17, #3a5a2c, #5a8040)",
      "cardBg": "rgba(255, 255, 255, 0.98)",
      "textPrimary": "#3a5a2c",
      "textSecondary": "rgba(58, 90, 44, 0.78)",
      "accent": "#3a5a2c",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(58, 90, 44, 0.35)",
      "buttonBg": "#3a5a2c",
      "buttonText": "#ffffff",
      "guestBoxBg": "rgba(58, 90, 44, 0.08)",
      "particleColors": [
        "#3a5a2c",
        "#5a8040",
        "#7da55c",
        "#aac98a",
        "#cfe0b8",
        "#e8f0dc",
        "#ffffff"
      ],
      "particleType": "flowers"
    },
    "fonts": {
      "couple": "\"DFVN New Eddy\", \"Fz Qellia\", cursive",
      "ampersand": "\"Alex Brush\", \"The Nautigal\", cursive"
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[74%] max-w-[300px] md:max-w-[360px] top-1/2 -translate-y-1/2 left-0 -translate-x-[35%] opacity-20 rotate-[20deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/chateau-green/hoanho2-1.webp"
        },
        {
          "className": "w-[74%] max-w-[300px] md:max-w-[360px] top-1/2 -translate-y-1/2 right-0 translate-x-[35%] opacity-20 scale-x-[-1] rotate-[5deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/chateau-green/hoanho3-1.webp"
        }
      ]
    }
  },
  "royal-blue": {
    "theme": {
      "background": "rgba(0, 10, 36, 0.98)",
      "cardBg": "linear-gradient(to bottom right, #00112E, #002875, #00112E)",
      "textPrimary": "#E1BC7C",
      "textSecondary": "rgba(225, 188, 124, 0.75)",
      "accent": "#E1BC7C",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(225, 188, 124, 0.4)",
      "buttonBg": "#E1BC7C",
      "buttonText": "#00112E",
      "guestBoxBg": "rgba(225, 188, 124, 0.08)",
      "particleColors": [
        "#E1BC7C",
        "#d4a85c",
        "#ffffff",
        "#f5e6c8"
      ],
      "particleType": "sparkles"
    },
    "fonts": {
      "couple": "\"Fz Qellia\", serif",
      "ampersand": null
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[80%] top-0 left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-20",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/royal-blue/flower.webp"
        },
        {
          "className": "w-[80%] bottom-0 left-1/2 -translate-x-1/2 translate-y-1/2 opacity-20 -scale-y-100",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/royal-blue/flower.webp"
        }
      ]
    }
  },
  "jasmine-white": {
    "theme": {
      "background": "linear-gradient(to bottom right, #404A1D, #5a6628, #404A1D)",
      "cardBg": "rgba(255, 250, 247, 0.98)",
      "textPrimary": "#404A1D",
      "textSecondary": "rgba(64, 74, 29, 0.75)",
      "accent": "#404A1D",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(64, 74, 29, 0.4)",
      "buttonBg": "#404A1D",
      "buttonText": "#ffffff",
      "guestBoxBg": "rgba(64, 74, 29, 0.08)",
      "particleColors": [
        "#d4e4a0",
        "#c8d88a",
        "#ffffff",
        "#eef4d0"
      ],
      "particleType": "petals"
    },
    "fonts": {
      "couple": "\"Fz Qellia\", serif",
      "ampersand": null
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[48%] top-0 left-0 opacity-25 -scale-x-100 -scale-y-100",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/moclan-white/hoa.webp"
        },
        {
          "className": "w-[48%] bottom-0 right-0 opacity-25",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/moclan-white/hoa.webp"
        }
      ]
    }
  },
  "dragon-phoenix-red": {
    "theme": {
      "background": "linear-gradient(to bottom right, #2a0404, #1a0202, #100101)",
      "cardBg": "#680e0e",
      "textPrimary": "#e9ce9e",
      "textSecondary": "rgba(233, 206, 158, 0.8)",
      "accent": "#e9ce9e",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(233, 206, 158, 0.5)",
      "buttonBg": "#e9ce9e",
      "buttonText": "#360202",
      "guestBoxBg": "rgba(233, 206, 158, 0.15)",
      "particleColors": [
        "#FFD700",
        "#e9ce9e",
        "#CD853F",
        "#FFC107"
      ],
      "particleType": "happiness"
    },
    "fonts": {
      "couple": "\"UNI Chu truyen thong\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": null,
    "decorations": {
      "cardImages": [
        {
          "className": "w-[200px] md:w-[280px] -top-[10px] -left-[70px] md:-top-[20px] md:-left-[90px] opacity-20",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/red-v1/rong.webp"
        },
        {
          "className": "w-[200px] md:w-[280px] -bottom-[40px] -right-[70px] md:-bottom-[140px] md:-right-[90px] opacity-20",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/red-v1/phuong.webp"
        },
        {
          "className": "w-[250px] md:w-[350px] top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-20",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/red-v1/bg-main.webp"
        }
      ]
    }
  },
  "royal-green": {
    "theme": {
      "background": "rgba(0, 14, 6, 0.98)",
      "cardBg": "linear-gradient(to bottom right, #001A08, #003F1E, #001A08)",
      "textPrimary": "#E1BC7C",
      "textSecondary": "rgba(225, 188, 124, 0.75)",
      "accent": "#E1BC7C",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(225, 188, 124, 0.4)",
      "buttonBg": "#E1BC7C",
      "buttonText": "#001A08",
      "guestBoxBg": "rgba(225, 188, 124, 0.08)",
      "particleColors": [
        "#E1BC7C",
        "#d4a85c",
        "#ffffff",
        "#f5e6c8"
      ],
      "particleType": "sparkles"
    },
    "fonts": {
      "couple": "\"Fz Qellia\", serif",
      "ampersand": null
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[80%] top-0 left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-20",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/royal-green/flower.webp"
        },
        {
          "className": "w-[80%] bottom-0 left-1/2 -translate-x-1/2 translate-y-1/2 opacity-20 -scale-y-100",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/royal-green/flower.webp"
        }
      ]
    }
  },
  "dragon-phoenix-v2-red": {
    "theme": {
      "background": "url('/chungdoi/images/themes/dragon-phoenix-v2-red/bg-frame.jpg') center/cover",
      "cardBg": "#680d0e",
      "textPrimary": "#e9ce9e",
      "textSecondary": "rgba(233, 206, 158, 0.8)",
      "accent": "#e9ce9e",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(233, 206, 158, 0.5)",
      "buttonBg": "#e9ce9e",
      "buttonText": "#4a0808",
      "guestBoxBg": "rgba(233, 206, 158, 0.15)",
      "particleColors": [
        "#D4A017",
        "#C41E3A",
        "#E8A735",
        "#B22222"
      ],
      "particleType": "happiness"
    },
    "fonts": {
      "couple": "\"Fz Qellia\", serif",
      "ampersand": null
    },
    "sealType": null,
    "decorations": {
      "cardImages": [
        {
          "className": "w-[200px] md:w-[280px] -top-[10px] -left-[70px] md:-top-[20px] md:-left-[90px] opacity-30",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/longphung-v2-red/phuong.webp"
        },
        {
          "className": "w-[200px] md:w-[280px] -bottom-[40px] -right-[70px] md:-bottom-[100px] md:-right-[90px] opacity-30",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/longphung-v2-red/rong.webp"
        },
        {
          "className": "w-[80px] md:w-[100px] top-2 right-2 md:top-3 md:right-3 opacity-20",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/longphung-v2-red/cloud.webp"
        }
      ]
    }
  },
  "cherry-blossom-pink": {
    "theme": {
      "background": "linear-gradient(to bottom right, #ba4a59, #ae4c51, #9e3c41)",
      "cardBg": "rgba(255, 245, 247, 0.95)",
      "textPrimary": "#8a3a45",
      "textSecondary": "rgba(138, 58, 69, 0.8)",
      "accent": "#ba4a59",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(186, 74, 89, 0.5)",
      "buttonBg": "#ba4a59",
      "buttonText": "#ffffff",
      "guestBoxBg": "rgba(186, 74, 89, 0.1)",
      "particleColors": [
        "#FFB6C1",
        "#FFC0CB",
        "#ffffff",
        "#FF69B4"
      ],
      "particleType": "petals"
    },
    "fonts": {
      "couple": "\"Fz Qellia\", serif",
      "ampersand": null
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-full bottom-0 left-0 opacity-20",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/anhdao-pink/2.webp"
        }
      ]
    }
  },
  "elegant-leaf-green": {
    "theme": {
      "background": "linear-gradient(to bottom right, #23381E, #1f3219, #1a2b15)",
      "cardBg": "rgba(255, 255, 255, 0.95)",
      "textPrimary": "#4E6439",
      "textSecondary": "rgba(78, 100, 57, 0.7)",
      "accent": "#4E6439",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(78, 100, 57, 0.5)",
      "buttonBg": "#4E6439",
      "buttonText": "#ffffff",
      "guestBoxBg": "rgba(78, 100, 57, 0.1)",
      "particleColors": [
        "#90EE90",
        "#98FB98",
        "#4E6439",
        "#bdcdc1"
      ],
      "particleType": "leaves"
    },
    "fonts": {
      "couple": "\"Fz Qellia\", serif",
      "ampersand": null
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[180px] md:w-[250px] -top-[30px] -right-[40px] md:-top-[40px] md:-right-[60px]",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/thanhdiep-green/la2.webp"
        },
        {
          "className": "w-[180px] md:w-[250px] -bottom-[30px] -left-[40px] md:-bottom-[40px] md:-left-[50px]",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/thanhdiep-green/la1.webp"
        }
      ]
    }
  },
  "boho-floral-brown": {
    "theme": {
      "background": "linear-gradient(to bottom right, #3d2112, #2e180d, #1f1008)",
      "cardBg": "rgba(255, 250, 247, 0.95)",
      "textPrimary": "#4a2816",
      "textSecondary": "rgba(74, 40, 22, 0.7)",
      "accent": "#846758",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(74, 40, 22, 0.5)",
      "buttonBg": "#4a2816",
      "buttonText": "#fffaf7",
      "guestBoxBg": "rgba(74, 40, 22, 0.1)",
      "particleColors": [
        "#c9a87c",
        "#846758",
        "#d4a574",
        "#e8c9a0"
      ],
      "particleType": "leaves"
    },
    "fonts": {
      "couple": "\"Fz Aghita\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[400px] md:w-[400px] -top-[40px] -right-[50px] md:-top-[50px] md:-right-[60px] opacity-40",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/boho-floral-brown/flower_top.webp"
        },
        {
          "className": "w-[160px] md:w-[220px] -bottom-[40px] -left-[40px] md:-bottom-[60px] md:-left-[50px] opacity-30 rotate-[160deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/boho-floral-brown/flower_bottom.webp"
        }
      ]
    }
  },
  "dragon-phoenix-blue": {
    "theme": {
      "background": "linear-gradient(to bottom right, #040e16, #020810, #010408)",
      "cardBg": "#0A202F",
      "textPrimary": "#e9ce9e",
      "textSecondary": "rgba(233, 206, 158, 0.8)",
      "accent": "#e9ce9e",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(233, 206, 158, 0.5)",
      "buttonBg": "#e9ce9e",
      "buttonText": "#030a11",
      "guestBoxBg": "rgba(233, 206, 158, 0.15)",
      "particleColors": [
        "#FFD700",
        "#e9ce9e",
        "#CD853F",
        "#FFC107"
      ],
      "particleType": "happiness"
    },
    "fonts": {
      "couple": "\"UNI Chu truyen thong\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": null,
    "decorations": {
      "cardImages": [
        {
          "className": "w-[200px] md:w-[280px] -top-[10px] -left-[70px] md:-top-[20px] md:-left-[90px] opacity-30",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/red-v1/rong.webp"
        },
        {
          "className": "w-[200px] md:w-[280px] -bottom-[40px] -right-[70px] md:-bottom-[140px] md:-right-[90px] opacity-30",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/red-v1/phuong.webp"
        },
        {
          "className": "w-[250px] md:w-[350px] top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-30",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/red-v1/bg-main.webp"
        }
      ]
    }
  },
  "double-phoenix-green": {
    "theme": {
      "background": "linear-gradient(to bottom right, #19472D, #122F1E, #0C2216)",
      "cardBg": "rgba(255, 240, 231, 0.95)",
      "textPrimary": "#19472D",
      "textSecondary": "rgba(25, 71, 45, 0.8)",
      "accent": "#19472D",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(25, 71, 45, 0.5)",
      "buttonBg": "#19472D",
      "buttonText": "#FFF0E7",
      "guestBoxBg": "rgba(25, 71, 45, 0.1)",
      "particleColors": [
        "#19472D",
        "#2D6A4F",
        "#52B788",
        "#FFF0E7"
      ],
      "particleType": "happiness"
    },
    "fonts": {
      "couple": "\"Fz Aghita\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": null,
    "decorations": {
      "cardImages": [
        {
          "className": "w-[120px] md:w-[220px] -top-[20px] -left-[20px] md:-top-[20px] md:-left-[50px] opacity-90 rotate-10",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/songphung-green/Phuong.webp"
        },
        {
          "className": "w-[140px] md:w-[220px] -bottom-[120px] -right-[40px]  md:-bottom-[110px] md:-right-[50px] opacity-90 -scale-x-100 rotate-5",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/songphung-green/Phuong.webp"
        },
        {
          "className": "w-[120px] md:w-[160px] -bottom-[20px] -left-[20px] md:-bottom-[30px] md:-left-[30px] opacity-60",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/songphung-green/HOA.webp"
        },
        {
          "className": "w-[100px] md:w-[140px] -top-[15px] -right-[15px] md:-top-[20px] md:-right-[20px] opacity-60 rotate-180",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/songphung-green/HOA.webp"
        }
      ]
    }
  },
  "nhat-binh-red": {
    "theme": {
      "background": "linear-gradient(165deg, #f8f3e0 0%, #f2ead2 45%, #ece0c4 100%)",
      "cardBg": "linear-gradient(to bottom right, #f8f3e0, #efe6d0, #f8f3e0)",
      "textPrimary": "#542e08",
      "textSecondary": "rgba(84, 46, 8, 0.88)",
      "accent": "#c32a29",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(84, 46, 8, 0.35)",
      "buttonBg": "#c32a29",
      "buttonText": "#f8f3e0",
      "guestBoxBg": "rgba(84, 46, 8, 0.06)",
      "particleColors": [
        "#c32a29",
        "#e8d4a8",
        "#6b4423",
        "#f8f3e0"
      ],
      "particleType": "happiness"
    },
    "fonts": {
      "couple": "__ASSET_VAR__",
      "ampersand": null
    },
    "sealType": null,
    "decorations": {
      "cardImages": []
    }
  },
  "qasr-green": {
    "theme": {
      "background": "linear-gradient(to bottom right, #5d6e53, #708465, #5d6e53)",
      "cardBg": "rgba(251, 248, 243, 0.98)",
      "textPrimary": "#708465",
      "textSecondary": "rgba(112, 132, 101, 0.78)",
      "accent": "#708465",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(112, 132, 101, 0.35)",
      "buttonBg": "#708465",
      "buttonText": "#ffffff",
      "guestBoxBg": "rgba(112, 132, 101, 0.08)",
      "particleColors": [
        "#d8e0cd",
        "#c4d0b4",
        "#fbf8f3",
        "#e2e8d5"
      ],
      "particleType": "flowers"
    },
    "fonts": {
      "couple": "\"DFVN New Eddy\", \"Fz Qellia\", cursive",
      "ampersand": null
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[58%] max-w-[300px] md:max-w-[340px] top-0 right-0 translate-x-[18%] -translate-y-[18%] opacity-90",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/qasr-green/flower-top.webp"
        },
        {
          "className": "w-[58%] max-w-[300px] md:max-w-[340px] top-0 left-0 -translate-x-[18%] -translate-y-[18%] -scale-x-100 opacity-90",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/qasr-green/flower-top.webp"
        },
        {
          "className": "w-[88%] max-w-[400px] md:max-w-[460px] bottom-0 left-1/2 -translate-x-1/2 translate-y-[43.5%] opacity-90",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/qasr-green/flower-bottom.webp"
        }
      ]
    }
  },
  "dragon-phoenix-green": {
    "theme": {
      "background": "linear-gradient(to bottom right, #080e07, #050905, #020402)",
      "cardBg": "#162614",
      "textPrimary": "#e9ce9e",
      "textSecondary": "rgba(233, 206, 158, 0.8)",
      "accent": "#e9ce9e",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(233, 206, 158, 0.5)",
      "buttonBg": "#e9ce9e",
      "buttonText": "#0a0f09",
      "guestBoxBg": "rgba(233, 206, 158, 0.15)",
      "particleColors": [
        "#FFD700",
        "#e9ce9e",
        "#CD853F",
        "#FFC107"
      ],
      "particleType": "happiness"
    },
    "fonts": {
      "couple": "\"UNI Chu truyen thong\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": null,
    "decorations": {
      "cardImages": [
        {
          "className": "w-[200px] md:w-[280px] -top-[10px] -left-[70px] md:-top-[20px] md:-left-[90px] opacity-30",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/red-v1/rong.webp"
        },
        {
          "className": "w-[200px] md:w-[280px] -bottom-[40px] -right-[70px] md:-bottom-[140px] md:-right-[90px] opacity-30",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/red-v1/phuong.webp"
        },
        {
          "className": "w-[250px] md:w-[350px] top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-30",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/red-v1/bg-main.webp"
        }
      ]
    }
  },
  "double-dragon-red": {
    "theme": {
      "background": "linear-gradient(to bottom right, #4a1212, #3a0e0e, #2a0808)",
      "cardBg": "#a31d16",
      "textPrimary": "#f0d497",
      "textSecondary": "rgba(240, 212, 151, 0.85)",
      "accent": "#f0d497",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(240, 212, 151, 0.5)",
      "buttonBg": "#f0d497",
      "buttonText": "#4a1212",
      "guestBoxBg": "rgba(0, 0, 0, 0.15)",
      "guestBoxBorder": "rgba(240, 212, 151, 0.3)",
      "particleColors": [
        "#FFD700",
        "#FFC107",
        "#FF6B6B",
        "#FFE066"
      ],
      "particleType": "happiness"
    },
    "fonts": {
      "couple": "\"Fz Aghita\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": null,
    "decorations": {
      "cardImages": [
        {
          "className": "w-[220px] md:w-[300px] -top-[50px] -left-[95px] md:-top-[80px] md:-left-[100px] opacity-30 rotate-[30deg] md:rotate-[30deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/songlong-red/dragon_left.webp"
        },
        {
          "className": "w-[220px] md:w-[300px] -bottom-[30px] -right-[120px] md:-bottom-[80px] md:-right-[110px] opacity-30 -rotate-[-30deg] md:-rotate-[-30deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/songlong-red/dragon_right.webp"
        },
        {
          "className": "w-[50px] md:w-[70px] top-3 right-3 md:top-4 md:right-4 opacity-40",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/songlong-red/cloud_small.webp"
        },
        {
          "className": "w-[50px] md:w-[70px] bottom-3 left-3 md:bottom-4 md:left-4 opacity-40 -scale-x-100",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/songlong-red/cloud_big.webp"
        },
        {
          "className": "w-[50px] md:w-[70px] bottom-2 left-1/2 -translate-x-1/2 opacity-20",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/songlong-red/wave.webp"
        }
      ]
    }
  },
  "minimalism-red": {
    "theme": {
      "background": "linear-gradient(to bottom right, #7C151A, #5a0e12, #3d090d)",
      "cardBg": "rgba(255, 255, 255, 0.95)",
      "textPrimary": "#7C151A",
      "textSecondary": "rgba(124, 21, 26, 0.8)",
      "accent": "#7C151A",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(124, 21, 26, 0.5)",
      "buttonBg": "#7C151A",
      "buttonText": "#FFFFFF",
      "guestBoxBg": "rgba(124, 21, 26, 0.1)",
      "particleColors": [
        "#7C151A",
        "#9B1B21",
        "#B52028",
        "#FFFFFF"
      ],
      "particleType": "hearts"
    },
    "fonts": {
      "couple": "\"Fz Aghita\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": null,
    "decorations": {
      "cardImages": [
        {
          "className": "w-[200px] md:w-[280px] top-[10px] -left-[20px] md:top-[10px] md:-left-[20px] opacity-80 rotate-[-25deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/minimalism-red/header-bottom-01.png"
        },
        {
          "className": "w-[200px] md:w-[280px] bottom-[10px] -right-[20px] md:bottom-[10px] md:-right-[20px] opacity-80 rotate-[-25deg] -scale-x-100",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/minimalism-red/header-bottom-01.png"
        }
      ]
    }
  },
  "brocade-flower-red": {
    "theme": {
      "background": "linear-gradient(to bottom right, rgba(74,21,3,0.92), rgba(106,33,4,0.92), rgba(138,48,16,0.92)), url(__ASSET_VAR__) center / 420px repeat",
      "cardBg": "rgba(248, 236, 219, 0.98)",
      "textPrimary": "#6a2104",
      "textSecondary": "rgba(60, 77, 32, 0.85)",
      "accent": "#6a2104",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(106, 33, 4, 0.35)",
      "buttonBg": "#6a2104",
      "buttonText": "#f8ecdb",
      "guestBoxBg": "rgba(106, 33, 4, 0.08)",
      "particleColors": [
        "#3c4d20",
        "#536e3e",
        "#6b7d3f",
        "#546c40"
      ],
      "particleType": "leaves"
    },
    "fonts": {
      "couple": "\"Fz Aghita\", \"Times New Roman\", serif",
      "ampersand": "\"Alex Brush\", \"The Nautigal\", cursive"
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[46%] max-w-[220px] top-0 left-0 -translate-x-[6%] -translate-y-[6%] opacity-95",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/brocade-flower-red/flower-corner.webp"
        },
        {
          "className": "w-[46%] max-w-[220px] top-0 right-0 translate-x-[6%] -translate-y-[6%] opacity-95 scale-x-[-1]",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/brocade-flower-red/flower-corner.webp"
        },
        {
          "className": "w-[120%] max-w-none bottom-0 left-1/2 -translate-x-1/2 translate-y-[22%] opacity-90",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/brocade-flower-red/dai-hoa.webp"
        }
      ]
    }
  },
  "silk-flora-brown": {
    "theme": {
      "background": "linear-gradient(to bottom right, #7a4d38, #996247, #7a4d38)",
      "cardBg": "rgba(250, 243, 232, 0.98)",
      "textPrimary": "#996247",
      "textSecondary": "rgba(153, 98, 71, 0.78)",
      "accent": "#996247",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(153, 98, 71, 0.35)",
      "buttonBg": "#996247",
      "buttonText": "#ffffff",
      "guestBoxBg": "rgba(153, 98, 71, 0.08)",
      "particleColors": [
        "#e8d4c4",
        "#dcc4b0",
        "#faf3e8",
        "#f0e2d5"
      ],
      "particleType": "petals"
    },
    "fonts": {
      "couple": "\"Fz Qellia\", serif",
      "ampersand": null
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[64%] max-w-[300px] md:max-w-[360px] top-1/2 -translate-y-1/2 left-0 -translate-x-1/2 opacity-[0.15] scale-x-[-1] rotate-[30deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/silkflora-brown/top-flower.webp"
        },
        {
          "className": "w-[72%] max-w-[340px] md:max-w-[400px] top-1/2 -translate-y-1/2 right-0 translate-x-1/2 translate-y-[12px] opacity-[0.15] scale-x-[-1]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/silkflora-brown/bottom.webp"
        }
      ]
    }
  },
  "chateau-blue": {
    "theme": {
      "background": "linear-gradient(to bottom right, #0c2147, #123467, #1a4080)",
      "cardBg": "rgba(255, 255, 255, 0.98)",
      "textPrimary": "#123467",
      "textSecondary": "rgba(18, 52, 103, 0.78)",
      "accent": "#123467",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(18, 52, 103, 0.35)",
      "buttonBg": "#123467",
      "buttonText": "#ffffff",
      "guestBoxBg": "rgba(18, 52, 103, 0.08)",
      "particleColors": [
        "#123467",
        "#3a5a8f",
        "#6f8cbf",
        "#a8bcd4",
        "#cfdcec",
        "#e6eef7",
        "#ffffff"
      ],
      "particleType": "flowers"
    },
    "fonts": {
      "couple": "\"DFVN New Eddy\", \"Fz Qellia\", cursive",
      "ampersand": "\"Alex Brush\", \"The Nautigal\", cursive"
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[64%] max-w-[300px] md:max-w-[360px] top-1/2 -translate-y-1/2 left-0 -translate-x-[35%] opacity-[0.18] rotate-[15deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/chateau-blue/hoa.webp"
        },
        {
          "className": "w-[64%] max-w-[300px] md:max-w-[360px] top-1/2 -translate-y-1/2 right-0 translate-x-[35%] opacity-[0.18] scale-x-[-1] rotate-[15deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/chateau-blue/hoa.webp"
        }
      ]
    }
  },
  "boho-floral-pink": {
    "theme": {
      "background": "linear-gradient(to bottom right, #6b2d3a, #4a1f28, #2e1219)",
      "cardBg": "rgba(255, 250, 247, 0.95)",
      "textPrimary": "#9D6D63",
      "textSecondary": "rgba(157, 109, 99, 0.7)",
      "accent": "#C4897F",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(157, 109, 99, 0.5)",
      "buttonBg": "#9D6D63",
      "buttonText": "#FFFAF7",
      "guestBoxBg": "rgba(157, 109, 99, 0.1)",
      "particleColors": [
        "#F5C6C9",
        "#BAB4C7",
        "#e8a8a0",
        "#d4b8b4"
      ],
      "particleType": "petals"
    },
    "fonts": {
      "couple": "\"Fz Aghita\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[360px] md:w-[450px] lg:w-[520px] -top-[50px] md:-top-[65px] lg:-top-[80px] left-[calc(-30%+60px)] md:left-[calc(-30%+75px)] lg:left-[calc(-30%+90px)] opacity-40",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/boho-floral-pink/asset_1.webp"
        },
        {
          "className": "w-[130px] md:w-[180px] -bottom-[40px] -right-[35px] md:-bottom-[50px] md:-right-[45px] opacity-30 rotate-[150deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/boho-floral-pink/asset_3.webp"
        }
      ]
    }
  },
  "dragon-phoenix-black": {
    "theme": {
      "background": "linear-gradient(to bottom right, #030303, #010101, #000000)",
      "cardBg": "#0a0a0a",
      "textPrimary": "#FFC662",
      "textSecondary": "rgba(255, 198, 98, 0.8)",
      "accent": "#FFC662",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(255, 198, 98, 0.5)",
      "buttonBg": "#FFC662",
      "buttonText": "#020202",
      "guestBoxBg": "rgba(255, 198, 98, 0.15)",
      "particleColors": [
        "#FFD700",
        "#FFC662",
        "#CD853F",
        "#FFC107"
      ],
      "particleType": "happiness"
    },
    "fonts": {
      "couple": "\"UNI Chu truyen thong\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": null,
    "decorations": {
      "cardImages": [
        {
          "className": "w-[200px] md:w-[280px] -top-[10px] -left-[70px] md:-top-[20px] md:-left-[90px] opacity-30",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/red-v1/rong.webp"
        },
        {
          "className": "w-[200px] md:w-[280px] -bottom-[40px] -right-[70px] md:-bottom-[140px] md:-right-[90px] opacity-30",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/red-v1/phuong.webp"
        },
        {
          "className": "w-[250px] md:w-[350px] top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-30",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/red-v1/bg-main.webp"
        }
      ]
    }
  },
  "song-hy-red": {
    "theme": {
      "background": "linear-gradient(to bottom right, #5a0000, #400000, #2a0000)",
      "cardBg": "#800000",
      "textPrimary": "#ffeed2",
      "textSecondary": "rgba(255, 238, 210, 0.85)",
      "accent": "#ffeed2",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(255, 238, 210, 0.5)",
      "buttonBg": "#ffeed2",
      "buttonText": "#800000",
      "guestBoxBg": "rgba(0, 0, 0, 0.15)",
      "guestBoxBorder": "rgba(255, 238, 210, 0.3)",
      "particleColors": [
        "#FFD700",
        "#FFC107",
        "#FF6B6B",
        "#FFE066"
      ],
      "particleType": "happiness"
    },
    "fonts": {
      "couple": "\"Fz Aghita\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": "happiness",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[220px] md:w-[300px] -top-[65px] -left-[124px] md:-top-[104px] md:-left-[130px] opacity-[0.15] rotate-[30deg] md:rotate-[30deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/song-hy-red/chu-hy.webp"
        },
        {
          "className": "w-[220px] md:w-[300px] -bottom-[39px] -right-[156px] md:-bottom-[104px] md:-right-[143px] opacity-[0.15] -rotate-[-30deg] md:-rotate-[-30deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/song-hy-red/chu-hy.webp"
        }
      ]
    }
  },
  "qasr-gold": {
    "theme": {
      "background": "linear-gradient(to bottom right, rgba(110,100,51,0.82), rgba(84,78,39,0.82), rgba(58,53,32,0.82)), url(__ASSET_VAR__) center / cover",
      "cardBg": "rgba(249, 241, 230, 0.98)",
      "textPrimary": "#544E27",
      "textSecondary": "rgba(84, 78, 39, 0.78)",
      "accent": "#544E27",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(84, 78, 39, 0.35)",
      "buttonBg": "#544E27",
      "buttonText": "#ffffff",
      "guestBoxBg": "rgba(84, 78, 39, 0.08)",
      "particleColors": [
        "#e7dfc9",
        "#d8cbab",
        "#f9f1e6",
        "#cdbf99"
      ],
      "particleType": "flowers"
    },
    "fonts": {
      "couple": "\"DFVN New Eddy\", \"Fz Qellia\", cursive",
      "ampersand": null
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[38%] md:w-[29%] max-w-[200px] md:max-w-[182px] top-1/2 left-0 -translate-x-[35%] -translate-y-1/2 opacity-70",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/qasr-gold/bush2.webp"
        },
        {
          "className": "w-[60%] md:w-[46%] max-w-[312px] md:max-w-[280px] top-1/2 right-0 translate-x-[35%] -translate-y-[42%] opacity-70",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/qasr-gold/bush1.webp"
        },
        {
          "className": "w-[96%] max-w-[460px] md:max-w-[520px] bottom-0 left-1/2 -translate-x-1/2 translate-y-[24%] opacity-70",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/qasr-gold/bush5.webp"
        }
      ]
    }
  },
  "double-dragon-blue": {
    "theme": {
      "background": "linear-gradient(to bottom right, #0f1a2e, #0a1222, #060d18)",
      "cardBg": "#1a3060",
      "textPrimary": "#f0d497",
      "textSecondary": "rgba(240, 212, 151, 0.85)",
      "accent": "#f0d497",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(240, 212, 151, 0.5)",
      "buttonBg": "#f0d497",
      "buttonText": "#0f1a2e",
      "guestBoxBg": "rgba(0, 0, 0, 0.15)",
      "guestBoxBorder": "rgba(240, 212, 151, 0.3)",
      "particleColors": [
        "#FFD700",
        "#FFC107",
        "#87CEEB",
        "#FFE066"
      ],
      "particleType": "happiness"
    },
    "fonts": {
      "couple": "\"Fz Aghita\", \"Baskerville\", \"Times New Roman\", serif",
      "ampersand": null
    },
    "sealType": null,
    "decorations": {
      "cardImages": [
        {
          "className": "w-[220px] md:w-[300px] -top-[50px] -left-[95px] md:-top-[80px] md:-left-[100px] opacity-30 rotate-[30deg] md:rotate-[30deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/songlong-red/dragon_left.webp"
        },
        {
          "className": "w-[220px] md:w-[300px] -bottom-[30px] -right-[120px] md:-bottom-[80px] md:-right-[110px] opacity-30 -rotate-[-30deg] md:-rotate-[-30deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/songlong-red/dragon_right.webp"
        },
        {
          "className": "w-[50px] md:w-[70px] top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-15",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/songlong-red/chinese_happiness.webp"
        },
        {
          "className": "w-[50px] md:w-[70px] top-3 right-3 md:top-4 md:right-4 opacity-40",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/songlong-red/cloud_small.webp"
        },
        {
          "className": "w-[50px] md:w-[70px] bottom-3 left-3 md:bottom-4 md:left-4 opacity-40 -scale-x-100",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/songlong-red/cloud_big.webp"
        },
        {
          "className": "w-[50px] md:w-[70px] bottom-2 left-1/2 -translate-x-1/2 opacity-20",
          "flyOnOpen": false,
          "src": "/chungdoi/images/themes/_decor/songlong-red/wave.webp"
        }
      ]
    }
  },
  "hoa-tinh-red": {
    "theme": {
      "background": "linear-gradient(165deg, #8B0000 0%, #C41230 45%, #8B0000 100%)",
      "cardBg": "linear-gradient(to bottom right, #FFFFFF, #FFF5F5, #FFFFFF)",
      "textPrimary": "#D70C1B",
      "textSecondary": "rgba(215, 12, 27, 0.85)",
      "accent": "#D70C1B",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(215, 12, 27, 0.25)",
      "buttonBg": "#D70C1B",
      "buttonText": "#FFFFFF",
      "guestBoxBg": "rgba(215, 12, 27, 0.05)",
      "particleColors": [
        "#FFD700",
        "#FFC107",
        "#FF6B6B",
        "#FFE066"
      ],
      "particleType": "happiness"
    },
    "fonts": {
      "couple": null,
      "ampersand": null
    },
    "sealType": null,
    "decorations": {
      "cardImages": []
    }
  },
  "baroque-gold": {
    "theme": {
      "background": "linear-gradient(to bottom right, rgba(138,90,42,0.9), rgba(185,125,62,0.9), rgba(216,175,135,0.9)), url(__ASSET_VAR__) center / 1200px repeat",
      "cardBg": "rgba(251, 248, 241, 0.98)",
      "textPrimary": "#B97D3E",
      "textSecondary": "rgba(141, 143, 88, 0.85)",
      "accent": "#B97D3E",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(185, 125, 62, 0.4)",
      "buttonBg": "#B97D3E",
      "buttonText": "#ffffff",
      "guestBoxBg": "rgba(185, 125, 62, 0.08)",
      "particleColors": [
        "#B97D3E",
        "#d8af87",
        "#e8d2b0",
        "#8D8F58",
        "#f3e9d6",
        "#ffffff"
      ],
      "particleType": "flowers"
    },
    "fonts": {
      "couple": "\"DFVN New Eddy\", \"Fz Qellia\", cursive",
      "ampersand": "\"Alex Brush\", \"The Nautigal\", cursive"
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[42%] max-w-[220px] top-0 left-0 -translate-x-[28%] -translate-y-[28%] opacity-50 rotate-[8deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/baroque-gold/hoa.webp"
        },
        {
          "className": "w-[42%] max-w-[220px] bottom-0 right-0 translate-x-[28%] translate-y-[28%] opacity-50 scale-x-[-1] rotate-[8deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/baroque-gold/hoa.webp"
        }
      ]
    }
  },
  "royal-red": {
    "theme": {
      "background": "rgba(40, 0, 1, 0.98)",
      "cardBg": "linear-gradient(to bottom right, #3E0001, #7A0003, #3E0001)",
      "textPrimary": "#E1BC7C",
      "textSecondary": "rgba(225, 188, 124, 0.75)",
      "accent": "#E1BC7C",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(225, 188, 124, 0.4)",
      "buttonBg": "#E1BC7C",
      "buttonText": "#3E0001",
      "guestBoxBg": "rgba(225, 188, 124, 0.08)",
      "particleColors": [
        "#E1BC7C",
        "#d4a85c",
        "#ffffff",
        "#f5e6c8"
      ],
      "particleType": "sparkles"
    },
    "fonts": {
      "couple": "\"Fz Qellia\", serif",
      "ampersand": null
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "w-[80%] top-0 left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-20",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/royal-red/flower.webp"
        },
        {
          "className": "w-[80%] bottom-0 left-1/2 -translate-x-1/2 translate-y-1/2 opacity-20 -scale-y-100",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/royal-red/flower.webp"
        }
      ]
    }
  },
  "crystal-floral-blue": {
    "theme": {
      "background": "linear-gradient(to bottom right, #163a5e, #215589, #2f6aa6)",
      "cardBg": "#fbf8f3",
      "textPrimary": "#215589",
      "textSecondary": "rgba(33, 85, 137, 0.78)",
      "accent": "#215589",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(33, 85, 137, 0.35)",
      "buttonBg": "#215589",
      "buttonText": "#fbf8f3",
      "guestBoxBg": "rgba(33, 85, 137, 0.08)",
      "guestBoxBorder": "rgba(33, 85, 137, 0.3)",
      "particleColors": [
        "#215589",
        "#3a6ba0",
        "#6f8cbf",
        "#a8bcd4",
        "#cfdcec",
        "#e6eef7",
        "#ffffff"
      ],
      "particleType": "flowers"
    },
    "fonts": {
      "couple": "\"DFVN New Eddy\", \"Fz Qellia\", cursive",
      "ampersand": "\"Alex Brush\", \"The Nautigal\", cursive"
    },
    "sealType": "heart",
    "decorations": {
      "cardImages": [
        {
          "className": "h-[65%] md:h-[82%] lg:h-[92%] w-auto max-w-none top-1/2 -translate-y-1/2 left-0 -translate-x-[40%] md:-translate-x-[20%] opacity-25 rotate-[25deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/crystal-floral-blue/flower2.webp"
        },
        {
          "className": "h-[65%] md:h-[82%] lg:h-[92%] w-auto max-w-none top-1/2 -translate-y-1/2 right-0 translate-x-[40%] md:translate-x-[20%] opacity-25 -rotate-[25deg]",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/crystal-floral-blue/flower3.webp"
        }
      ]
    }
  },
  "co-ba-red": {
    "theme": {
      "background": "linear-gradient(165deg, #4a3428 0%, #352518 45%, #241a12 100%)",
      "cardBg": "linear-gradient(to bottom right, #f8f3e0, #efe6d0, #f8f3e0)",
      "textPrimary": "#542e08",
      "textSecondary": "rgba(84, 46, 8, 0.88)",
      "accent": "#c32a29",
      "dividerFrom": "transparent",
      "dividerTo": "rgba(84, 46, 8, 0.35)",
      "buttonBg": "#c32a29",
      "buttonText": "#f8f3e0",
      "guestBoxBg": "rgba(84, 46, 8, 0.06)",
      "particleColors": [
        "#CC0033",
        "#B80030",
        "#FF0040",
        "#AA0028"
      ],
      "particleType": "confetti"
    },
    "fonts": {
      "couple": null,
      "ampersand": null
    },
    "sealType": null,
    "decorations": {
      "cardImages": [
        {
          "className": "w-[115%] max-w-none left-1/2 top-[calc(12%_-_30px)] -translate-x-1/2 opacity-20",
          "flyOnOpen": true,
          "src": "/chungdoi/images/themes/_decor/coba-red/cho-ben-thanh.webp"
        }
      ]
    }
  }
};
